// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TokenService is an autogenerated mock type for the TokenService type
type TokenService struct {
	mock.Mock
}

// Generate provides a mock function with given fields: fileId, key, exp
func (_m *TokenService) Generate(fileId string, key string, exp int64) (string, error) {
	ret := _m.Called(fileId, key, exp)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string, int64) string); ok {
		r0 = rf(fileId, key, exp)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, int64) error); ok {
		r1 = rf(fileId, key, exp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Verify provides a mock function with given fields: tokenStr, fileId, key
func (_m *TokenService) Verify(tokenStr string, fileId string, key string) error {
	ret := _m.Called(tokenStr, fileId, key)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(tokenStr, fileId, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
