// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AppValidator is an autogenerated mock type for the AppValidator type
type AppValidator struct {
	mock.Mock
}

// Validate provides a mock function with given fields: i
func (_m *AppValidator) Validate(i interface{}) error {
	ret := _m.Called(i)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(i)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateValue provides a mock function with given fields: i, tag
func (_m *AppValidator) ValidateValue(i interface{}, tag string) error {
	ret := _m.Called(i, tag)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, string) error); ok {
		r0 = rf(i, tag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
