// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo"

	mock "github.com/stretchr/testify/mock"
)

// ScanHandler is an autogenerated mock type for the ScanHandler type
type ScanHandler struct {
	mock.Mock
}

// Health provides a mock function with given fields: c
func (_m *ScanHandler) Health(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Information provides a mock function with given fields: c
func (_m *ScanHandler) Information(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ScanFiles provides a mock function with given fields: c
func (_m *ScanHandler) ScanFiles(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ScanUrls provides a mock function with given fields: c
func (_m *ScanHandler) ScanUrls(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
