// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"file-uploader/src/httpapp"
	"file-uploader/src/httpapp/httpappcontext"
)

import (
	_ "github.com/joho/godotenv/autoload"
)

// Injectors from wire.go:

func InitializeApp(appSetting httpappcontext.AppSettingContext) (*httpappcontext.AppContext, error) {
	appContext := httpapp.Initialize(appSetting)
	return appContext, nil
}
